"""Initial migration after model changes

Revision ID: 04eed7c1a8ad
Revises: c2baddb64f37
Create Date: 2025-04-28 18:31:25.743105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04eed7c1a8ad'
down_revision = 'c2baddb64f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=300), nullable=True),
    sa.Column('skill', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.String(length=500), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('total_income', sa.Integer(), nullable=True),
    sa.Column('work', sa.Text(), nullable=True),
    sa.Column('jobs', sa.String(length=300), nullable=True),
    sa.Column('skills_needed', sa.String(length=300), nullable=True),
    sa.Column('contact_details', sa.String(length=300), nullable=True),
    sa.Column('interest', sa.String(length=300), nullable=True),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('income_awarded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_opportunity_id')
        batch_op.drop_index('ix_applications_user_id')

    op.drop_table('applications')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index('ix_opportunities_created_by')

    op.drop_table('opportunities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index('ix_opportunities_created_by', ['created_by'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('opportunity_id', sa.INTEGER(), nullable=False),
    sa.Column('applied_at', sa.DATETIME(), nullable=False),
    sa.Column('income_awarded', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_applications_opportunity_id', ['opportunity_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(length=300), nullable=True),
    sa.Column('skills', sa.VARCHAR(length=200), nullable=True),
    sa.Column('experience', sa.VARCHAR(length=500), nullable=True),
    sa.Column('qualification', sa.VARCHAR(length=200), nullable=True),
    sa.Column('total_income', sa.INTEGER(), nullable=False),
    sa.Column('work', sa.TEXT(), nullable=True),
    sa.Column('jobs', sa.VARCHAR(length=300), nullable=True),
    sa.Column('skills_needed', sa.VARCHAR(length=300), nullable=True),
    sa.Column('contact_details', sa.VARCHAR(length=300), nullable=True),
    sa.Column('interest', sa.VARCHAR(length=300), nullable=True),
    sa.Column('availability', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=1)

    op.drop_table('application')
    op.drop_table('opportunity')
    op.drop_table('user')
    # ### end Alembic commands ###
