"""Add income_awarded to Application

Revision ID: 33e5a3e9d055
Revises: 759b3b93c3db
Create Date: 2025-04-28 15:58:14.030809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e5a3e9d055'
down_revision = '759b3b93c3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_awarded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('income_awarded')

    # ### end Alembic commands ###
