"""Extended User model for seeker and provider profile fields

Revision ID: b81203ddb57d
Revises: 50b81f2e57b4
Create Date: 2025-04-28 15:07:48.854756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81203ddb57d'
down_revision = '50b81f2e57b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('total_income', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('work', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('jobs', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('skills_needed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_details', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact_details')
        batch_op.drop_column('skills_needed')
        batch_op.drop_column('jobs')
        batch_op.drop_column('work')
        batch_op.drop_column('total_income')
        batch_op.drop_column('qualification')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
