"""empty message

Revision ID: fcd7fbe9fa66
Revises: 
Create Date: 2025-04-25 18:47:30.903521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd7fbe9fa66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('skill', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('interest', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])  # ✅ named constraint
        batch_op.drop_column('username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('uq_user_email', type_='unique')  # ✅ drop by name
        batch_op.drop_column('availability')
        batch_op.drop_column('interest')
        batch_op.drop_column('experience')
        batch_op.drop_column('skill')
        batch_op.drop_column('name')
        batch_op.drop_column('role')
        batch_op.drop_column('email')
    # ### end Alembic commands ###
